site_name: FXDOCS
site_url: https://docs.fxtelekom.org

theme:
  name: material
  logo: /assets/logo.webp
  favicon: /assets/logo.webp
  features:
    - navigation.footer
    - navigation.top
    - toc.follow

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Bevezető: index.md
  - Első lépések:
    - Első lépések: first/first.md
    - Wireguard telepítés: first/install.md
    - Beállítás: first/setup.md
  - Router beállítások:
    - Mikrotik: router/Mikrotik.md
    - Asus: router/asus.md
    - OPNSense: router/OPNSense.md
  - Egyéb infók:
    - Szolgáltatások: other/services.md
    - Adatkezelési nyilatkozat: other/privacy.md
    - A DTAG problémáról: other/dtag.md

extra:
  social:
    - icon: simple/discord
      link: https://discord.gg/n2WmGaEn3H
    - icon: simple/github
      link: https://github.com/fxtelekom
    - icon: simple/kofi
      link: https://ko-fi.com/fxtelekom
  
copyright: © 2024 FXTELEKOM

plugins:
  - search
  - git-authors
  - i18n:
      docs_structure: folder
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: hu
          default: true
          name: Magyar
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Bevezető: Introduction
            Első lépések: First steps
            Wireguard telepítés: Wireguard installation
            Beállítás: Setup
            Router beállítások: Router settings
  - git-revision-date-localized:
      enable_creation_date: true


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
